# Generated by Django 3.0.8 on 2020-07-29 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('ID', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('FoodGroup', models.CharField(max_length=25, verbose_name='Food Group')),
                ('Calories', models.CharField(max_length=6, verbose_name='Calories')),
                ('Fat', models.CharField(max_length=6, verbose_name='Fat(g)')),
                ('Protein', models.CharField(max_length=6, verbose_name='Protein(g)')),
                ('Carbohydrate', models.CharField(max_length=6, verbose_name='Carbohydrate(g)')),
                ('Sugars', models.CharField(max_length=6, verbose_name='Sugars(g)')),
                ('Fiber', models.CharField(max_length=6, verbose_name='Fiber(g)')),
            ],
            options={
                'db_table': 'food',
            },
        ),
    ]
