# Generated by Django 3.0.8 on 2020-08-01 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(verbose_name='Description')),
            ],
            options={
                'ordering': ['-created_datetime'],
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Ingredient')),
                ('quantity', models.FloatField(verbose_name='Quantity')),
                ('units', models.CharField(blank=True, max_length=50, null=True, verbose_name='Units')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='foodapp.Recipe')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RecipeStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField()),
                ('description', models.TextField(verbose_name='Description')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='foodapp.Recipe')),
            ],
            options={
                'ordering': ['rank'],
                'unique_together': {('rank', 'recipe')},
            },
        ),
    ]
